### PR TITLE
Added: Prettier Code formatter Config

### PR DESCRIPTION
**Pull request by RatakondalaArun**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant.

### What is the current behavior?

- Does not have code formatting rules.

### What is the new behavior?

This PR adds the Prettier Code Formatter config. 
Different people use different code formatters, to make 
life easy for code reviewers we can follow a single code formatting rules.

*This is the current config*
```
printWidth: 100
trailingComma: "all"
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: false
arrowParens: always
```

### Other information?

- **This pull request doesn't have any breaking changes.**
- **No tests are needed**.

### CODE REVIEW

**Comment by monizb** [comment]
Hey @RatakondalaArun I would like to inform you that right now this repository runs @restyled-commits  as a code formatter which automatically reviews each PR and formats the code to have a consistent style, so Prettier is not required here :)

**Comment by RatakondalaArun** [comment]
I didn't see that coming.🙂

---
I see your codebase is completely dependent on the firebase library.
It will be better if we can create an abstract layer. I can help you with that

**Comment by monizb** [comment]
> It will be better if we can create an abstract layer. I can help you with that
I didn't get you here, could you please elaborate? @RatakondalaArun

**Comment by monizb** [comment]
Please open a new issue when you are ready, thanks!

**Pull request closed without merging**
