### PR TITLE
Show tooltip for first 5 seconds

### PR DESCRIPTION
**Pull request by prashantacharya**
### Please check if the PR fulfils these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant
* [x] I am not raising a spam PR or a PR that fixes spellings or whitespaces for Hacktoberfest
* [ x I know that if this PR is found to be spam, It will be labelled and reported immediately

### What is the current behaviour?
It doesn't show any information to the user when he logs in to the application.

### What is the new behaviour?
My solution displays a tooltop on the + button for the first time the component gets mounted to the DOM.

#### Screenshot
image

### Other information?
1. Is this a breaking change?
No, this is just a minor change.

2. How did you test
I tested the component manually.

Please request changes/modifications if you like what I've tried to do.

### CODE REVIEW

**Comment by monizb** [comment]
@prashantacharya if this is the tooltip you were talking about, it looks fine also you can add this image when there are no links in thr centre of the page: https://icons8.com/illustrations/illustration/pixeltrue-search

**Comment by prashantacharya** [comment]
@monizb will be doing it in midday at my work break :+1:

**Comment by prashantacharya** [comment]
@monizb I am not being able to write to the database? What might be the issue? I've turned on permission for read and write on my firebase console too.

**Comment by monizb** [comment]
> @monizb I am not being able to write to the database? What might be the issue? I've turned on permission for read and write on my firebase console too.

Looks like you have not pulled in the latest changes, the DB structure and rules have changed, deploy the new rules mentioned in `firestore.rules` file and try again

**Pull request closed without merging**
