### PR TITLE
Show a Dialog after each link is created 

### PR DESCRIPTION
**Pull request by paultech4u**
### What is the current behavior?
"
* [ ] Implements a share button to share URL.
* [ ] Implements a QR Code scan.
* [ ] JPG image sharing not fixed.

### What is the new behavior?
1.  When the URL card is created show the share dialog.
chrome-capture (1)
2. Added a share button to the card for sharing the URL.
chrome-capture

### CODE REVIEW

**Comment by monizb** [comment]
@paultech4u thank you soo much for the PR! 🥳🥳🥳 Can you please make it so that the dialog box has the short url (only the code) part in bold in the centre above the sharing options with the copy button on the right of the short url and when clicked it should automatically take the current domain, like it already does and shows a small message that it has been copied :)
Also there are a lot of conflicts in your PR with the master branch, I request you to pull in all the latest changes and test the url sharing again and then commit.

**Comment by paultech4u** [comment]
The short URL is the same as the custom URL the problem now is that the short URL is not a valid URL I don't know if you are aware of these
chrome-capture
 issues.

**Comment by monizb** [comment]
@paultech4u I didn't get you there, you mean if i enter the long url in the short url as well, its not valid? Because the screenshot shown only material in short URL

**Comment by paultech4u** [comment]
@monizb I have resolved all the in my branch please do check it.

**Comment by monizb** [comment]
@paultech4u still looks like you have many conflicts, please rectifiy them im adding the accepted label as of now

**Comment by paultech4u** [comment]
@monizb I have resolved the issues.

**Pull request closed without merging**
