### PR TITLE
Login page issue solved #165

### PR DESCRIPTION
**Pull request by Amit366**
Has solved the login page issue #165

### CODE REVIEW

**Comment by monizb** [comment]
Hey @Amit366 congratulations on the amazing work you have done, i really like the animation element, here are few more changes you can do before we push this in :) 
Screenshot 2021-01-11 at 3 15 10 PM

**Comment by monizb** [comment]
@Amit366 also please edit the Firebase.js back to the original file and please use a .env file before adding the next push to this PR, because right now the app is using your firebase credentials

**Comment by monizb** [comment]
Screenshot 2021-01-11 at 3 28 38 PM
<br>
Looks like you have edited something within the application also, all the buttons have disappeared , please check this as well

**Comment by Amit366** [comment]
No sir I haven't done anything

**Comment by Amit366** [comment]
I just focused on the login page

**Comment by monizb** [comment]
> I just focused on the login page

Yes you wouldn't have done it on purpose, Material UI shares its properties across many components
So you might have changed the styling of something resulting in the change of other designs

**Comment by Amit366** [comment]
i installed material icon dependencies for the email and password icons

**Comment by monizb** [comment]
Screenshot 2021-01-11 at 3 39 30 PM
<br>
This is how the original dashboard looks like :)

**Comment by Amit366** [comment]
Sir what should I do now?

**Comment by monizb** [comment]
> Sir what should I do now?

You need to re-verify your css styling changes which u have made, you have mistakenly edited some other components as well. Create class names for every part, dont directly target the elements

**Comment by Amit366** [comment]
Sir ,I rechecked it properly and also executed the suggested changes except the  box on the left side.

**Comment by Amit366** [comment]
why am i getting the restyled error?

**Comment by monizb** [comment]
Screenshot 2021-01-11 at 5 14 44 PM

@Amit366 the logo is too huge now, you have still not fixed the dashboard looks like, also the firebase credentials are still visible

**Comment by Amit366** [comment]
sir should I delete the material icons dependencies to fix the dashboard?

**Comment by Amit366** [comment]
And for the firebase I have asked in the discord on how to add.

**Comment by Amit366** [comment]
Screenshot (19)

**Comment by Amit366** [comment]
Sir the dashboard looks like this on my screen

**Comment by Amit366** [comment]
Screenshot (20)

**Comment by Amit366** [comment]
After adding a link it looks like this

**Comment by Amit366** [comment]
Sir after creating the .env file the website isn't working now.

**Comment by Amit366** [comment]
Screenshot (21)

**Comment by Amit366** [comment]
Screenshot (22)

**Comment by monizb** [comment]
> After adding a link it looks like this

Yes thats not what it should look like, please refer the initial image which i sent you

**Comment by monizb** [comment]
> Sir after creating the .env file the website isn't working now.

I dont see any errors on the console what is the error?

**Comment by Amit366** [comment]
> > Sir after creating the .env file the website isn't working now.
> 
> I dont see any errors on the console what is the error?

On the webpage its showing "FirebaseError: projectId must be a string in FirebaseApp.options"

**Comment by monizb** [comment]
> > > Sir after creating the .env file the website isn't working now.
> > 
> > 
> > I dont see any errors on the console what is the error?
> 
> On the webpage its showing "FirebaseError: projectId must be a string in FirebaseApp.options"

Okay no issues for the time being while u are working on it just do the old way, but when u push changes please change it back to the older way

**Comment by Amit366** [comment]
But sir I completed all the work.  But what to do with the icons?

**Comment by Amit366** [comment]
Sir can you suggest me on what to do to get back the icons

**Comment by monizb** [comment]
@Amit366 when is this program ending? Tomorrow ill check your code and try to fix it, its just a styling error

**Comment by Amit366** [comment]
So can I send the PR now?

**Comment by Amit366** [comment]
I mean the changes which I made

**Comment by monizb** [comment]
> So can I send the PR now?

This itself is the PR right?

**Comment by Amit366** [comment]
Sir I have updated some changes . Please review it.

**Comment by Amit366** [comment]
Sir I request. Can u make it level 4 as I made the whole login page from the start. So seeing my work if you feel, then please make it level 4. It's just a request.

**Comment by Amit366** [comment]
Sir one request. Can u make it level 4 as I made the whole login page from the start. So seeing my work if you feel, then please make it level 4. It's just a request.

**Pull request closed without merging**
