### PR TITLE
Added contrbuting.md

### PR DESCRIPTION
**Pull request by OverthinkersArea**
Added CONTRBUTING.md file and created a image folder inside public folder for images related to CONTRBUTING.md.

### CODE REVIEW

**Comment by monizb** [comment]
Hey @OverthinkersArea thank you for the wonderful contribution I'm going ahead and merging this pull request

**Comment by monizb** [comment]
@all-contributors please add @OverthinkersArea  for Documentation

**Comment by OverthinkersArea** [comment]
pls add  "hacktoberfest-accepted" label to this pull request @monizb

**Comment by OverthinkersArea** [comment]
> Hey @OverthinkersArea thank you for the wonderful contribution I'm going ahead and merging this pull request

thanks man

**Comment by monizb** [comment]
> pls add "hacktoberfest-accepted" label to this pull request @monizb

Hey @OverthinkersArea you dont need that label as long as it has been merged

**Pull request merged**
