### PR TITLE
Feature password protection

### PR DESCRIPTION
**Pull request by harshvats2000**
### Issue solved
#14 

### Behaviour now
If the short url is not protected, it redirect the user to destination url as usual.
If the short url is protected, the main screen will be prompted with an input box which will ask for password.

### What is not done yet??
1. Ui of input boxes and buttons is not done.
2. The option to lock and unlock the short url can only be seen in list view and not in module view.

### CODE REVIEW

**Comment by monizb** [comment]
Hey @harshvats2000 thanks for the PR 🥳 Please provide screenshots and gifs to reduce PR Review time thanks :)

**Comment by harshvats2000** [comment]
fireshort
Hope this will clear the new feature. The UI is not improved yet. Maybe will spend time for UI in future :)

**Comment by monizb** [comment]
@harshvats2000 thanks for the amazing PR 🥳🥳 I have reviewed this PR and will be working on the UI Part too! Thanks once again :)

**Comment by monizb** [comment]
@all-contributors add @harshvats2000 for Code

**Pull request merged**
