### PR TITLE
Create contribution.md

### LINKED ISSUE #23: Add a meaningful CONTRIBUTING.md file
To comply fully with Github's community standards a well documented CONTRBUTING.md file is required to help first time contributors to contribute to this repository. You can use this guide [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to write a good one

### PR DESCRIPTION
**Pull request by ronin-07**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [x] Documentation has been updated/added if relevant

### What is the current behavior?

Closes #23

### CODE REVIEW

**Comment by monizb** [comment]
Hey @ronin-07 thanks for the PR although this does not satisfy the needs of a good CONTRIBUTING file. Please find some useful links below which should help you draft a better file which helps contributors
Some good examples [here](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) and [here](https://github.com/badges/shields/blob/master/CONTRIBUTING.md)
You can add links to Firebase documentation, How to spread the word, Advantages Of Open Source etc.
`Please note that you have 2 days to refactor this PR after which it will be labeled invalid` Thank you 👍🏼

**Review by Dheeraj-01 — APPROVED** [review]
It is a wonderful help for beginners

**Comment by monizb** [comment]
Hey @ronin-07 #32 adds this file as a result this PR will be marked invalid , thanks for contributing :)

**Comment by monizb** [comment]
@ronin-07 this file has been created in #32 as a result this PR will be marked inavlid. Thank you for your contribution :)

**Pull request closed without merging**
