### PR TITLE
:rocket: other: using cloudfare service to get user IP

### LINKED ISSUE #7: Reduce IP Tracking Time while redirecting to the destination link
The app takes a minimum of 5 seconds to capture the User's IP Address When Redirecting to the destination link which is not at all ideal, It will be great if you can reduce this time drastically by using an alternative npm package or a free api. Right now it uses `public-api` package from NPM

### PR DESCRIPTION
**Pull request by PranjalAgni**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant
* [x] I am not raising a spam PR or a PR that fixes spellings or whitespaces for Hacktoberfest
* [x] I know that if this PR is found to be spam, It will be labeled and reported immediately

### What is the current behavior?
Fixes #7 

### What is the new behavior?
Using Cloudfare services to get user IP reduces time more than 50%

### CODE REVIEW

**Comment by monizb** [comment]
@PranjalAgni ill be checking this tomorrow until then i am accepting this PR :)

**Comment by PranjalAgni** [comment]
@monizb  Hey any progress on the code review part

**Comment by monizb** [comment]
Hey @PranjalAgni sorry for the stale close, can you please let me know if the Cloudfare API requires any kind of key?

**Comment by PranjalAgni** [comment]
> Hey @PranjalAgni sorry for the stale close, can you please let me know if the Cloudfare API requires any kind of key?

No API key is required

**Pull request closed without merging**
