### PR TITLE
Fixes #41 Confirm dialog on URL delete event added

### LINKED ISSUE #41: Add confirmation dialog before deleting a link
**Is your feature request related to a problem? Please describe.**
Right now the created links are deleted as soon as "Delete" is clicked, this is not ideal

**Describe the solution you'd like**
Add a confirmation dialog which first asks the user if they want to delete the link or not

### PR DESCRIPTION
**Pull request by i-aryan**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant
* [ ] I am not raising a spam PR or a PR that fixes spellings or whitespaces for Hacktoberfest
* [ ] I know that if this PR is found to be spam, It will be labeled and reported immediately

### What is the current behavior?

When a user tries to delete a URL, it directly deletes it without any confirmation dialog.
### What is the new behavior?
Issue #41 
Added a confirm dialog for the event when an admin deletes a URL.

### CODE REVIEW

**Comment by monizb** [comment]
@i-aryan Thanks for the PR!! I see that you have used window.prompt for the confirmation which is not ideal i request you to use `react-confirm-alert` npm package which already exists within the app and has been used in a few places.

**Comment by i-aryan** [comment]
@monizb Oh okay. I'll make the changes quickly and let you know.

**Comment by i-aryan** [comment]
@monizb Made the changes. Please review.

**Comment by monizb** [comment]
@i-aryan thats perfect, thank you for contributing!!

**Comment by monizb** [comment]
@all-contributors please add @i-aryan for Code

**Pull request merged**
