### PR TITLE
Added changes to README.md

### PR DESCRIPTION
**Pull request by bereketsemagn**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Fixed README.md, added titles, and made it neater

### What is the new behavior?
More organized, and neater

### CODE REVIEW

**Comment by monizb** [comment]
Hey @bereketsemagn I don't see any changes being made except you adding "Introducing Fireshort" and you adding yourself conveniently onto the Contributions table. Please provide more info on what you have changed

**Comment by bereketsemagn** [comment]
I've made it neater, with the introduction title. @monizb.

**Comment by monizb** [comment]
@bereketsemagn How does that make that neater may I know? And on what basis have you added your name onto the Contributions table?

**Comment by bereketsemagn** [comment]
I can edit it more, but that's what I have for now. It also gives people an introduction to what this is @monizb

**Comment by monizb** [comment]
@bereketsemagn thank you for the contribution, I am marking this PR invalid and spam as of now because this doesn't add any value to the Repository and will not count towards Hacktoberfest fest too.

**Pull request closed without merging**
