### PR TITLE
Signup feature, added pages: Signup.js, ForgotPassord.js, EmailNotVerified.js

### PR DESCRIPTION
**Pull request by abhinavkrin**
I have added the signup functionality with signup, password recovery, and email verification feature. Will add a separate admin panel for each user in the next commit.

### What is the current behavior?
The app does not have a signup page.

### What is the new behavior?
1. adds signup page
2. add the password recovery page.
3. Sign up is verified using email verification.

### Other issues fixed.
1. The logout button throws an error. "dispatch is not a function". Fixed it.
2. Fixed the issue in which the login button showed circular progress even after login failed.
3. When hosted on the server, the app homepage redirected to http://localhost:3000/admin. It should use the current domain name instead. Fixed it.
4. Modified firebase.json and added firestore rules file, so the security rules are deployed from the command line.

#### Links:
A live example of the current behavior could be found on https://fireurls.web.app/

#### Routes added:
/signup
/forgot-password

### Other information?
Is this a breaking change? No

### CODE REVIEW

**Comment by monizb** [comment]
@abhinavkrin First of all I would like to congratulate you for upholding the values of Hacktoberfest and making a PR which adds soo much value to this repository.Thanks a lot!! 🎉🎉

1) I found that I am unable to access the forgot password page from the url, it redirects me back to the login page. Also it'd be great if you could add a link to the forgot password page from the login page

2) Since the Firestore rules are set to write only if authenticated, this would not work when you try to access a link with activity tracking turned on in Incognito since the app will not be able to save ip information onto the DB. Hence I would suggest we have better Db design which secures user information from being accessed only by that particular user, and having a different collection for user tracking information to be stored.

I would really love to have your inputs and advice on the second part on how to make the DB more efficient,Secure and Scalable :)

**Comment by abhinavkrin** [comment]
1. Ops. I forgot to deploy the latest build. Sorry my bad.
2. Will add public write access to the tracking collection. But set the delete access to tracking collection to false.

**Comment by monizb** [comment]
@abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!

**Comment by abhinavkrin** [comment]
> @abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!

Hey @monizb, As I was working with the admin panel. I found out that the way the password is checked is insecure. The document has read access set to "public". And hence the password is exposed to the public. Also, once a password is set I could not find a way to remove the password.

Please look into the matter.
A solution would be to set a flag called "isProtected" set to true and storing the passwords in another collection.

**Comment by monizb** [comment]
> > @abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!
> 
> Hey @monizb, As I was working with the admin panel. I found out that the way the password is checked is insecure. The document has read access set to "public". And hence the password is exposed to the public. Also, once a password is set I could not find a way to remove the password.
> 
> Please look into the matter.
> A solution would be to set a flag called "isProtected" set to true and storing the passwords in another collection.

@abhinavkrin are you talking about the link passwords?

**Comment by abhinavkrin** [comment]
> > > @abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!
> > 
> > 
> > Hey @monizb, As I was working with the admin panel. I found out that the way the password is checked is insecure. The document has read access set to "public". And hence the password is exposed to the public. Also, once a password is set I could not find a way to remove the password.
> > Please look into the matter.
> > A solution would be to set a flag called "isProtected" set to true and storing the passwords in another collection.
> 
> @abhinavkrin are you talking about the link passwords?

Yes.

**Comment by monizb** [comment]
> > > > @abhinavkrin that's not a problem, I'll keep the PR open so you can push all your commits and have one review and testing once you are ready. Thanks!
> > > 
> > > 
> > > Hey @monizb, As I was working with the admin panel. I found out that the way the password is checked is insecure. The document has read access set to "public". And hence the password is exposed to the public. Also, once a password is set I could not find a way to remove the password.
> > > Please look into the matter.
> > > A solution would be to set a flag called "isProtected" set to true and storing the passwords in another collection.
> > 
> > 
> > @abhinavkrin are you talking about the link passwords?
> 
> Yes.

Ok sure thanks for pointing that out! I'll have a look at it tomorrow and clean up and test all the code before merging in more PRs

**Comment by abhinavkrin** [comment]
@monizb Hey, I have added the admin panel and improved DB structure.
DB Structure:
hits/{curl} -> each document will have curl, hits, and author.
shorturls/{curl} -> the original Shorturl document
shorturls/{curl}/tracking/{trackId} -> the originaltracking document
settings/{uid} -> each doc will have settings 'viewMode'. More settings attributes can be added to this document.
I have added the rules in the 'firestore.rules' file.

Admin Panel:
Users can now see and edit only the links they have created.

I have deployed my version on http://fireurls.web.app/

**Comment by monizb** [comment]
@abhinavkrin thank you soo much for all the work you have put in to this!  would love to get this merged but looks like there a few conflicts in cardurls.js and login.js because of the recent changes. Please let me know if you could git pull, refactor and push another commit so that I dont have to manually resolve the conflicts. Thanks!

**Comment by abhinavkrin** [comment]
Conflicts resolved. @monizb

**Comment by monizb** [comment]
Thank you @abhinavkrin

**Comment by monizb** [comment]
@all-contributors add @abhinavkrin for Code and Bugs

**Pull request merged**
