### PR TITLE
Added Search functionality

### PR DESCRIPTION
**Pull request by asi309**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Implements #42
### What is the new behavior?
The link docs are stored in redux for realtime search using search bar. On login, the retrieved links are set to redux store.

### CODE REVIEW

**Comment by monizb** [comment]
Hey @asi thanks for the PR can you please provide screenshots of the new search box and also maybe a gif please? This will help us review your PR more efficiently thanks :)

**Comment by asi309** [comment]
> Hey @asi thanks for the PR can you please provide screenshots of the new search box and also maybe a gif please? This will help us review your PR more efficiently thanks :)
ss

**Comment by monizb** [comment]
Hey @asi309 there seems to be some conflict with the master branch, do you mind opening a new PR for the same? thanks!

**Comment by asi309** [comment]
> Hey @asi309 there seems to be some conflict with the master branch, do you mind opening a new PR for the same? thanks!

Any changes you want?

**Comment by asi309** [comment]
So, why new PR?

**Comment by monizb** [comment]
@asi309 that's because git merged it into the base branch without resolving conflicts and i had to revert this PR, so I will need a new PR to incorporate your changes, hope you understand.

**Comment by asi309** [comment]
Okay I understand, but after a PR is merged, I delete the fork, so now, only you may have any copy of the changes

**Comment by asi309** [comment]
> @asi309 that's because git merged it into the base branch without resolving conflicts and i had to revert this PR, so I will need a new PR to incorporate your changes, hope you understand.

I just restored the files, tested on my env and did a PR. Please confirm issues with merge. Thank You :)
https://github.com/monizb/FireShort/pull/57#issue-496418272

**Pull request merged**
