### PR TITLE
login page revamped

### PR DESCRIPTION
**Pull request by vikashgaya916**
The is related to the change requested in #2

### CODE REVIEW

**Comment by monizb** [comment]
Hey @vikashgaya916 thanks for the PR! The page looks much better now. Some changes to consider:
1) Remove Welcome to Fireshort and the logo from the left part
2) Add the Fireshort cursive logo which you see everywhere above login on right side.
3) Add a few feature cards with white background above or below the image showing some key features of the app
4) (If you can) make the left background animated slightly so that it doesn't look very static
5) Fix issues raised by access lint

If you do the above and send me a final screenshot it would be wonderful, thanks a lot! :)

**Comment by vikashgaya916** [comment]
Login-Page-2

@monizb Here is the screenshot after taking the changes from you into account. 

Also, the feature cards are scaled on hover and the background on left side keeps changing from black to dark-gray (and reverse) infinitely with 5 sec of each change loop

**Comment by monizb** [comment]
@vikashgaya916  that looks awesome! Thanks a lot for the PR 🥳🥳🥳, Keep contributing and being awesome!

**Comment by monizb** [comment]
@all-contributors add @vikashgaya916 for Design

**Pull request merged**
