### PR TITLE
Create analytics page

### PR DESCRIPTION
**Pull request by WillianRod**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [x] Documentation has been updated/added if relevant
* [x] I am not raising a spam PR or a PR that fixes spellings or whitespaces for Hacktoberfest
* [x] I know that if this PR is found to be spam, It will be labeled and reported immediately

### What is the current behavior?

Now, you can only see the amount of hits of a shortened link.

### What is the new behavior?
Added a new page in `/analytics/CURL` that will display all that data so you can see how many people clicked on the link per day, the total of clicks today, clicks per browser, clicks per OS.

### Other information?

I had to change the format of the `timestamp` saved on firebase. Before it was saving the date as a `localeString` to `ISOString`, this change is necessary so you can create a standard of dates saved on the database, because here in Brazil for exemple, the locale string is `05/10/2020` and other places can have a different locale string too.

### Preview
image

Link to #113

### CODE REVIEW

**Comment by monizb** [comment]
@WillianRod thanks for the PR! I tried running this PR and when i navigate to the analytics page, this is what I get:
Screenshot 2020-10-06 at 10 31 30 AM

Maybe I am doing something wrong here, can you please help me out?

**Comment by WillianRod** [comment]
I'll check on that now

**Comment by WillianRod** [comment]
image

Problem fixed. I did a rebase with the new changes from master, but didn't see that were changes on the permissions.

Now I'll work on map chart

**Comment by WillianRod** [comment]
image

image

Added the map chart showing clicks by country. I think this is good for now

**Comment by monizb** [comment]
@WillianRod my god sorry for the delay, I don't know how I missed this I'll be checking this tomorrow  until then I am adding the Hacktoberfest-accepted 
label.Thank you soo much :)

**Comment by monizb** [comment]
@WillianRod thank you for the amazing PR 🥳🥳🥳

**Comment by monizb** [comment]
@all-contributors add @WillianRod for Code and Design please

**Pull request merged**
