### PR TITLE
implemented code splitting

### LINKED ISSUE #168: Implement Code Splitting Using lazy()
Right now the app downloads about 300kb of data just to redirect to the link which reduces the speed of the app and hinders  User's experience.So it would be a very good idea to implement Code Splitting using Lazy() to remove slow load times and make it nearly negligible.

Resources:
1) https://reactjs.org/docs/code-splitting.html
2) https://web.dev/code-splitting-suspense/

### PR DESCRIPTION
**Pull request by peanub07**
I have implemented react code splitting

closes #168

### CODE REVIEW

**Comment by pranab2021** [comment]
I am a DWOC participant. Please consider labelling my PR for DWOC

**Comment by monizb** [comment]
@pranab2021 thank you for the PR, on running your PR, I haven't found any increase in speed yet, looks like you have not yet implemented code splitting properly yet, also please look at these images below, the UI has been messed up by your code:

Screenshot 2021-01-20 at 10 53 12 AM
Screenshot 2021-01-20 at 10 53 41 AM

**Comment by pranab2021** [comment]
oh, i didnt notice that. I will try to solve it

**Comment by pranab2021** [comment]
Hi @monizb, I have resolved UI issue. The loader is now removed from Home and put in App.js Suspense fallback. 

I Hope everything is working fine. If any issue is there request for changes😁

I am sorry i took too much time. I was looking through the codebase to find how things are working

**Comment by monizb** [comment]
> Hi @monizb, I have resolved UI issue. The loader is now removed from Home and put in App.js Suspense fallback.
> 
> I Hope everything is working fine. If any issue is there request for changes😁
> 
> I am sorry i took too much time. I was looking through the codebase to find how things are working
> 
> UI after this commit:--
> image

Hey! Sure give me some time and ill check this out today :)

**Comment by monizb** [comment]
@pranab2021 I am still able to see the following page:
<br/>
Screenshot 2021-02-01 at 10 58 46 AM

**Comment by pranab2021** [comment]
okay.. i will see about that

**Pull request closed without merging**
