### PR TITLE
Revamp Login Page

### PR DESCRIPTION
**Pull request by RitikPandey1**
### Please check if the PR fulfills these requirements:

* [x] The PR title and message describe the solution briefly.
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Old login page #2 

### What is the new behavior?
I have changed font style , add new avatar ,add new icons on text field and also changed text field style

### CODE REVIEW

**Comment by monizb** [comment]
Hey @RitikPandey1 thanks for the contribution! I request you to please provide corresponding Screenshots/Gifs of the changes made by you for easy review of your pull request :)

**Comment by RitikPandey1** [comment]
desgin2


@monizb

**Comment by monizb** [comment]
@RitikPandey1 although this is a good enhancement, it doesn't satisfy the needs of a "revamp" , below I am sharing a few ideas with you which you can potentially use and make the page much more beautiful

ex1
ex2
ex3

`Please note that you will have to refactor your code within the next 5 days after which this PR will be marked invalid`

**Comment by RitikPandey1** [comment]
des2

@monizb new desgin

**Comment by vikashgaya916** [comment]
@monizb I would like to try the revamp of the login page. Is it up for grabs?

**Comment by monizb** [comment]
Hey @vikashgaya916 please go ahead, please make sure that the login page is really beautiful and minimalistic like the reference screenshots :) I am assigning you to this Issue

**Pull request closed without merging**
