### PR TITLE
Login Page UI Revamp

### PR DESCRIPTION
**Pull request by niyasmhdth**
### What is the current behavior?
Existing UI changes need UI Revamp

### What is the new behavior?
Added Lottie package for small interactive animations

### CODE REVIEW

**Comment by monizb** [comment]
Hey @niyasmhdth thanks for the PR, although this is only partially correct and will require a lot of ammends:

1) Remove the main background Image
2) Remove the big card in the page and make the form fit like the login screen, both the sides have to stretch to entire screen
3) The right background image does match the theme but does not match the purpose of fireshort, maybe you could use a minimalistic vector design background, the animation is perfect!
4) Reduce Login Text size, make it centre aligned with the form
5) The main Fireshort logo should be removed to be just text like the logo you see in the admin panel on the top or on the loading screen.

Also you are having a lot of conflicts with the master branch, please pull in the latest changes and then make the changes, thanks!

**Comment by niyasmhdth** [comment]
@monizb Ok I'm on fixing it 👍🏽

**Comment by monizb** [comment]
@niyasmhdth are you still doing it?

**Comment by niyasmhdth** [comment]
@monizb yep, i have made another PR, there was an issue with my Local GIT

**Pull request closed without merging**
